### ISSUE TITLE
bizarre zig compilation error on commented out Go code in zig src file

### ISSUE THREAD

**Issue by zigster64** [karlseguin/zul#5]
This is a good one, and quite funny  !

0.14.0-dev.823+624fa8523 on Mac intel. Don't know if Mac arm64 has the same issue yet.

src/datetime.zig:1007:2: error: expected statement, found 'invalid token'
 //  us := rand.Int63n(31536000000000000)

same thing happens in web socket lib 

handshake.zig:55:5: error: expected statement, found 'invalid token'
    //  Connection: keep-alive, Upgrade

Not a problem with your code, but ... looks like its uncovered an interesting compiler bug.

At first I thought it might be the incompatible Go code in a comment tripping up sema, but on closer inspection, looks like its the presence of a colon in a comment.

Working on a patch to Zig to fix :)

**Comment by karlseguin** [comment]
Had https://github.com/karlseguin/websocket.zig/pull/40 on websocket.zig re tab in a comment this morning.

**Comment by zigster64** [comment]
oh - its a tab in a comment ?

that's weird. ok thanks. Still a zig bug then - good catch

Yeah, can't reproduce with a simple test app with commented out Go code

**Comment by karlseguin** [comment]
https://github.com/ziglang/zig/pull/20885

https://github.com/ziglang/zig-spec/issues/38


This is the new reality I guess.
